// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxwoisdnnwvyhlxbsyxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4d29pc2Rubnd2eWhseGJzeXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNDYzNDMsImV4cCI6MjA3NzcyMjM0M30.aJN5e1ZUeEfqYdIGT2Mnsf0qGPPc3IScasuvGbTg40I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});